spring:
  application:
    name: wor
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j9c103.p.ssafy.io:3306/wor?serverTimezone=Asia/Seoul
    username: wor
    password: workingrobot
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    hiddenmethod:
      filter: enabled=true

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: "1996Cjswo1026!"
    key-alias: wor

---
spring:
  application:
    name: wor
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j9c103.p.ssafy.io:3306/wor?serverTimezone=Asia/Seoul
    username: wor
    password: workingrobot
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    hiddenmethod:
      filter: enabled=true

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: "1996Cjswo1026!"
    key-alias: wor
